name: gbtofasta
owner: yating-l
description: Convert GenBank records to fasta, create table with coding regions information for each mRNA record and create a Trix index with coding regions information
homepage_url: http://hgdownload.cse.ucsc.edu/admin/exe/
type: unrestricted
categories: 
- Convert Formats
exclude:
  - tool_test_output.html
  - tool_test_output.json
